### ISSUE TITLE
dig in Alpine Linux

### ISSUE THREAD

**Issue by tinuva** [sequenceiq/docker-alpine-dig#3]
Hi,

There is already a package in Alpine Linux that contains the 'dig' binary.

Package 'bind' has 4 sub packages (at least in version 3.5 that I looked at).
One of the sub packages is called 'bind-tools'.
https://pkgs.alpinelinux.org/package/v3.5/main/x86_64/bind-tools

Contents of 'bind-tools':
https://pkgs.alpinelinux.org/contents?branch=v3.5&name=bind-tools&arch=x86_64&repo=main

**Comment by lalyos** [comment]
Thanks, but providing an alpine package, was just a side task. The main reason for this repo is, to have a statically compiled dig. So the [released](https://github.com/sequenceiq/docker-alpine-dig/releases) package can be used on any linux by a simple `curl | tar`
